### ISSUE TITLE
Code Dumped when Running Chrome

### ISSUE THREAD

**Issue by aseptilena** [tommyoshaw/arc-welder#3]
I use ubuntu 16.04 as Host OS.

I have followed all of your instructions carefully, but an error happened.

In container running, I got this warning.
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.

after I run this command...
google-chrome --user-data-dir=/data

I got this...

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Illegal instruction (core dumped)

I have used --no-sandbox, but it's not working or did not solved my issue.

**Comment by vincentcheng62** [comment]
try running docker with --security-opt seccomp:unconfined

**Comment by tomwillfixit** [comment]
Thanks Vincent. README updated and confirmed this is working on Ubuntu 16.04 host.
